### ISSUE TITLE
Help with reference error

### ISSUE THREAD

**Issue by vikingau** [Terricide/ReVision#2]
Hi, 

I am getting this error in the Website project mainform where it tries to instantiate a new PictureBrowser.

The type 'System.Windows.Forms.Form' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Windows.Forms' 

C:\GitHub\ReVision\src\WindowsFormsLib\MainForm.cs Line 77

Of course adding the reference creates more conflicts with ReVision.Forms.

How to fix the problem and run the website project?

Apologies if this is a stupid question...

Geoff

**Comment by Terricide** [comment]
WindowsFormsLib should have a reference to Microsoft's System.Windows.Forms.dll
WebSite should not have a reference to WindowsFormsLib but inside WebSite it should contain links to all the files in WindowsFormsLib.

Hope that makes sense. I'm going to download the project fresh and see if I can see the issue.

**Comment by Terricide** [comment]
Also WebSite should not have a reference for System.Windows.Forms

**Comment by vikingau** [comment]
Thanks, Adding the correct reference and checking the linked files (all OK), much more progress.
Got a compile, and browser launch, then a series of JavaScript runtime errors.
Browser IE11, Windows 10, VS2013R2.
Should I be upgrading to VS2015?

Do you want to take this offline into email so as not to clutter the project?

I haven't done much at all with JavaScript, so if its not an easy one I will go away and learn some more rather than trouble you at this early stage.

Fantastic work though...

Geoff

Exception was thrown at line 1238, column 4 in http://localhost/WebSite/scripts/jquery-2.1.4.js
0x800a139e - JavaScript runtime error: SyntaxError
Exception was thrown at line 1256, column 4 in http://localhost/WebSite/scripts/jquery-2.1.4.js
0x800a139e - JavaScript runtime error: SyntaxError
Exception was thrown at line 37, column 60610 in http://localhost:8778/ef884709ff1d4832a500a9487ef1cbb4/browserLink
0x800a139e - JavaScript runtime error: SyntaxError
Exception was thrown at line 1187, column 5850 in http://localhost:8778/ef884709ff1d4832a500a9487ef1cbb4/browserLink
0x800a138f - JavaScript runtime error: Unable to get property 'resolvedPath' of undefined or null reference
Exception was thrown at line 1187, column 5850 in http://localhost:8778/ef884709ff1d4832a500a9487ef1cbb4/browserLink
0x800a138f - JavaScript runtime error: Unable to get property 'resolvedPath' of undefined or null reference
Exception was thrown at line 1187, column 5850 in http://localhost:8778/ef884709ff1d4832a500a9487ef1cbb4/browserLink
0x800a138f - JavaScript runtime error: Unable to get property 'resolvedPath' of undefined or null reference
Exception was thrown at line 1187, column 5850 in http://localhost:8778/ef884709ff1d4832a500a9487ef1cbb4/browserLink
0x800a138f - JavaScript runtime error: Unable to get property 'resolvedPath' of undefined or null reference
This last error repeated indefinitely until browser was closed...

**Comment by Terricide** [comment]
It needs to be an IIS website project not IIS express as IIS express doesn't support websockets and websockets have to be installed.

I used visual studio 2015 but 2013 should be fine

**Comment by Terricide** [comment]
I don't mind taking the conversation offline but this thread might be useful for someone giving this a try

**Comment by vikingau** [comment]
Ok, I'm happy to run the thread online.
Server is 'LocalIIS' so should be OK? 
I had NuGet restore the packages. jQuery is 2.1.4, kendo 2015.3.1111

Had to create _references.js according to "~/Scripts/_references.js not found" message in JavaScript Language Service output tab

Now hunting down first chance exception "System.UnauthorisedAccessException" - I am assuming this is because I am running the project from my GitHub repository, which I don't normally do.

I will confirm back after I fix this error.
Geoff

**Comment by Terricide** [comment]
It probably is a permissions issue. The user account the application pool is running under doesn't have permission to access the dlls.

The easiest fix is to give the everyone group full control to the source code directory.

**Comment by vikingau** [comment]
Seem to have got around that permissions issue without making any changes.
But, I did update all NuGets to the latest respective versions.
I'm getting a blank page and no errors.
Have tried MainForm.aspx, Form.aspx and left it blank/default...
Any suggestion?
Cheers.

**Comment by Terricide** [comment]
It should be Default.aspx.

Can you put a break point in the javascript file script.js? in the onready function?

Does it ever connect to the WSHandler websocket class?

**Comment by vikingau** [comment]
Hi, no 'onready' function in script.js (or anything else in the project) - just a $().ready declaration.
Doesn't break at .ready function.
Tried default.aspx, which was what I originally set (sorry forgot to mention above).
Happy Easter.

**Comment by vikingau** [comment]
Put breakpoints in wshandler - no break.
I am getting a lot of syntax/intellisense messages in scripts.js, first one is:
Message 155 JSCS: Cannot parse invalid JavaScript   C:\GitHub\ReVision\src\WebSite\scripts\script.js    1   1   WebSite
File is identical to your file here & local repo only has changes relating to the NuGet updates.
I've tried with Chrome and IE11, but not Firefox or Edge.
Have a nice holiday - I'm going to stop for a day or so.
Geoff

**Comment by alprinias** [comment]
Hi,

To summarize my experience with the reference errors  and IIS I also encountered: 
1. Using VS 2013, I first accepted the prompt to target .NET Framework 4.5 (instead of 4.6.1 which I do not have installed) in 3 out of the 4 projects (see later for the 4th one)
2. When trying to build, I had 67 errors coming mainly from not being able to find System.Windows.Forms namespace ("Forms" part was underlined)
3. Website project referenced WindowsFormsLib, which I removed according to Mark's instruction above.
4. ReVision.Forms reference had a yellow triangle next to it. It turned out that this was from the fact that this project was targeting .NET 4.5.1, while the project that was using it (WebSite) had been converted to target 4.5. Visual Studio had NOT prompt me to change the target of ReVision project cause it was targeting originally 4.5.1 which is installed in my machine. Changing the target to 4.5 made the triangle disappear. Lesson learned: if converting to previous version of Visual Studio, make sure the projects target consistent .NET Framework versions. 

After that the rebuild worked correctly. 

However, I get an empty default.aspx page and two prompts from Google Chrome, 1. undefined and 2. disconnected. 

Check my IIS installation... I have a Windows 10 machine (ugraded from win 7). According to my registry key HKLM\SOftware\Microsoft\InetStr\VersionString my IIS Version is 10.0. Went to Features and Programs and checked Windows components and IIS I checked the WebSockets protocol to install the feature.

And... voila!!! The default.aspx page shows up correctly.!

Hope this helps some people.

Best wishes for everybody having a holiday this weekend... 

Alex

**Comment by Terricide** [comment]
Thanks Alex I put your steps in the main readme. I'll see if I can fix a couple of the issues and commit them.

**Comment by Terricide** [comment]
I downgraded all the project files to 4.5 and removed the WindowsFormLib reference from WebSite. So hopefully this will make it easier. I'm also thinking about swapping to SignalR so that IIS Express will work with it.

**Comment by Terricide** [comment]
I got it working with IIS Express 8. It just needed the port as part of the websocket url.

This should hopefully make it a ton easier to try with these latest changes
